export default {
    INITIATE_REQUEST: 0,
    SERVER_SUCCESS: 1,
    SERVER_FAILURE: 2,
    SUBMIT_ANSWER_CORRECT: 3,
    GET_NEXT_QUESTION: 4,
    SET_FEEDBACK: 5,
    CLEAR_FEEDBACK: 6,
    GET_USER: 7
};
